library(tidyverse)
library(ambient)
library(ggforce)
library(scico)

# Helper functions --------------------------------------------------------

#' Randomly select n scico palettes
#' @param seed Random seed
#' @param n Number of palettes to sample
#' @return A character vector of palette names
sample_scico_palette <- function(seed, n = 1) {
  scico_palette_names() |> 
    sample(n, replace = TRUE)
}

#' Randomly select noise parameters
#' @param seed Random seed
#' @return A list of noise parameters
sample_noise <- function(seed) {
  set.seed(seed)

  # noise parameter options
  frequency <- seq(0.125, 4, 0.125)
  octaves <- 2^(0:5)
  step <- 10^(-3:-1)
  
  # sample parameter combination
  list(noise = gen_perlin, 
       frequency = sample(frequency, 1),
       octaves = sample(octaves, 1),
       step = sample(step, 1))
}

#' Randomly select background noise parameters
#' @param seed Random seed
#' @return A list of noise parameters
sample_bg_noise <- function(seed) {
  set.seed(seed)
  
  # noises <- c(gen_simplex, gen_perlin, gen_spheres, gen_cubic)
  noises <- c(gen_simplex, gen_perlin, gen_cubic)
  octaves <- 2^(0:5)
  
  list(noise = sample(noises, 1), 
       octaves = sample(octaves, 1))
}

#' Shift data points by fractal curl noise
#' @param data A tibble with columns x, y, iter
#' @param params A list of noise parameters from sample_noise()
#' @return A tibble with redefined columns x, y, iter
add_fractal_curl <- function(data, params) {
  curl <- curl_noise(generator = params$noise[[1]], x = data$x, y = data$y, 
                     fractal = fbm, frequency = params$frequency, octaves = params$octaves)
  data |> mutate(x = x + params$step * curl$x, 
                 y = y + params$step * curl$y,
                 iter = iter + 1)
}


# Define data -------------------------------------------------------------

#' Generate data for plotting flow-like art
#' @param data Tibble of initial data points with columns x, y
#' @param seed Random seed
#' @param n Number of iterations
#' @param bg_res Resolution of background raster image
#' @return Tibble to be used by draw_art()
build_art <- function(data, seed, n, bg_res = 1000) {
  
  # sample noise parameters
  noise_params <- sample_noise(seed)
  bg_params <- sample_bg_noise(seed)
  
  set.seed(seed)
  
  # define background raster image
  bg <- long_grid(x = seq(0, 1, length.out = bg_res),
                  y = seq(0, 1, length.out = bg_res)) |>
    # colors as fractal noise defined by bg_params
    mutate(id = fracture(bg_params$noise[[1]], fbm, 
                         octaves = bg_params$octave, x = x, y = y),
           id = normalize(id),
           cat = "bg")
  
  # define plotted data points
  data |> 
    mutate(id = gen_perlin(x, y),
           iter = 1,
           cat = "point") |> 
    # iterate curl noise n times
    accumulate(1:n, ~add_fractal_curl(.x, noise_params), .init = _) |> 
    bind_rows() |> 
    mutate(across(c(x, y, id), normalize)) |> 
    bind_rows() |> 
    # add background data
    bind_rows(bg) |> 
    as_tibble()
}

# Define figure -----------------------------------------------------------

#' Draw flow-like art
#' @param d Tibble generated by build_art()
#' @param palette Color palette from scico
#' @return A ggplot object
draw_art <- function(d, palette) {
  d |> 
    ggplot(aes(x = x, y = y)) +
    # background as raster image
    geom_raster(data = filter(d, cat == "bg"), aes(fill = id)) +
    # foreground as points
    geom_point(data = filter(d, cat == "point"), 
               aes(color = id, size = -iter)) +
    scale_color_scico(palette = palette) +
    scale_fill_scico(palette = palette) +
    scale_size_continuous(range = c(0.02, 4)) +
    theme_void() +
    theme(legend.position = "none",
          plot.margin = margin(-2, -2, -2, -2, "in"))
}

# Draw figures ------------------------------------------------------------

# initialize 50x50 grid
d <- long_grid(x = seq(0, 1, length.out = 50),
               y = seq(0, 1, length.out = 50)) 

# draw figures for different seeds and iteration counts 
tibble(seed = 1:100,
       n = rep(seq(200, 2000, 200), 10)) |> 
  pwalk(~ build_art(d, ..1, ..2) |>
          draw_art(sample_scico_palette(..1)) |>
          ggsave(paste0("fig/flows", ..1, "n", ..2, ".png"), plot = _,
                 height = 12, width = 20))