library(tidyverse)
library(ambient)
library(ggforce)

# Helper functions --------------------------------------------------------

#' Shift data points by fractal curl noise
#' @param data A tibble with columns x, y, iter
#' @param step Step size
#' @return A tibble with redefined columns x, y, iter
add_fractal_curl <- function(data, step = 0.01) {
  curl <- curl_noise(generator = gen_simplex, x = data$x, y = data$y)
  data |> mutate(x = x + step * curl$x, 
                 y = y + step * curl$y,
                 iter = iter + 1)
}

# Define data -------------------------------------------------------------

#' Generate data for plotting watercolor blob
#' @param data Tibble of initial data points with columns x, y
#' @param seed Random seed
#' @param n Number of iterations
#' @param step Step size
#' @return Tibble to be used by draw_art()
build_art <- function(data, seed, n = 100, step = 0.01) {
  
  set.seed(seed)
  
  data |> 
    mutate(iter = 1) |> 
    # iterate curl noise n times
    accumulate(1:n, ~add_fractal_curl(.x, step), .init = _) |> 
    bind_rows() |> 
    mutate(across(c(x, y), normalize)) |> 
    bind_rows() |> 
    mutate(iter = paste(iter, id))
}

# Define figure -----------------------------------------------------------

#' Draw watercolor blob
#' @param d Tibble generated by build_art()
#' @param palette A vector of two colors for gradient shading within layers
#' @param alpha Transparency of each layer
#' @return A ggplot object
draw_art <- function(d, palette, alpha = 0.01) {
  d |> 
    ggplot(aes(x = x, y = y)) +
    # create sheer polygon layers to build up blob
    geom_polygon(aes(group = iter, fill = id), alpha = alpha) +
    scale_fill_gradient(low = palette[1], high = palette[2]) +
    coord_fixed() +
    theme_void() +
    theme(legend.position = "none")
}

# Draw figures ------------------------------------------------------------

# define circle outline
circle <- tibble(theta = seq(0, 2*pi, length = 200),
                 x = cos(theta)*1.2,
                 y = sin(theta)*1.2)

# define initial data points as grid + circle outline
d <- long_grid(x = seq(-1, 1, length.out = 20),
               y = seq(-1, 1, length.out = 20)) |> 
  bind_rows(circle) |> 
  mutate(pos = abs(x*y),
         id = cut(pos, 4, labels = 1:4),
         id = -as.numeric(id))

# draw figures with different initializations
tibble(
  # random seed
  seed = 1:20, 
  # number of layers
  n = rep(seq(100, 400, 100), 5),
  # color from colors()
  color = sample(1:657, 20)
) |> 
  pwalk(~ build_art(d, ..1, ..2, 0.008) |>
          # gradient from consecutive colors from colors()
          draw_art(colors()[..3:(..3+1)], 0.008) |>
          ggsave(paste0("fig/watercolor", ..1, "n", ..2, ".png"), plot = _,
                 height = 8, width = 8))
